#!/bin/bash
#
#algarvud
#
echo -n "Sisesta suvaline arv: "
read arv
summa=2

if [ $arv -eq 0 -o $arv -eq 1 ]; then
	echo "$arv - ei ole algarv"
fi
if [ $arv -eq $summa ]; then
	echo "$arv - on algarv"
fi
while [ $summa -lt $arv ]
do
	if [ `expr $arv %summa` -eq 0 ]
	then
		echo "$arv - ei ole algarv
		exit
	fi
	summa=$(($summa + 1))
		echo "$arv on algarv"
		exit
done
#
#skripti lõpp
#
