#!/bin/bash
#
#tärnid
echo -n "Sisesta ridade arv: "
read r
for (( i = $r; i >= 1; i-- ))
	do
		echo -n "$i"
		for (( j = 1; j <= $i; j++ ))
			do
				echo -n "*"
		done
		echo ""
	done
#
#skripti lõpp
#
